### ISSUE TITLE
Stm-link v2 flash error

### ISSUE THREAD

**Issue by duguguang** [bitcraze/crazyflie2-nrf-bootloader#7]
nokov@nokov-Host:~/work/cf/crazyflie2-nrf-bootloader$ make flash
openocd -d2 -f interface/stlink-v2.cfg  -f target/nrf51_stlink.tcl -c init -c targets -c "reset halt" \
                 -c "flash write_image erase cload_nrf.hex" -c "verify_image cload_nrf.hex" \
                 -c "mww 0x4001e504 0x01" -c "mww 0x10001080 0x3A000" -c "reset run" -c shutdown
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
debug_level: 2
WARNING: target/nrf51_stlink.cfg is deprecated, please switch to target/nrf51.cfg
Info : auto-selecting first available session transport "hla_swd". To override use 'transport select <transport>'.
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 1000 kHz
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : clock speed 950 kHz
Info : STLINK v2 JTAG v29 API v2 SWIM v7 VID 0x0483 PID 0x3748
Info : using stlink api v2
Info : Target voltage: 2.840557
Info : nrf51.cpu: hardware has 6 breakpoints, 4 watchpoints
    TargetName         Type       Endian TapName            State       
--  ------------------ ---------- ------ ------------------ ------------
 0* nrf51.cpu          hla_target little nrf51.cpu          halted
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x080002bc msp: 0x20005000
auto erase enabled
Warn : Unknown device (HWID 0x00000000)
Error: Bank is invalid

make: *** [Makefile:104: flash] Error 1

**Comment by duguguang** [comment]
but i flash the stm32 bootloader fine

**Comment by knmcguire** [comment]
I just tried this on a crazyflie just now, I don't see any problems with flashing this, You probably need to solder an adapter for the NRF chip, see https://www.bitcraze.io/products/debug-adapter-kit/ under 'usage'. Maybe you have been flashing the STM all along?

Anyway, if you have any problems in the future, it is better to start a  github discussion first at https://discussions.bitcraze.io/  as we handle all support in the future.
